FROM node:current-alpine

# Create app directory
WORKDIR /usr/src/app

# Install dependencies
COPY package.json .
RUN npm install
RUN npm install bcrypt

# Bundle app source
COPY . ./

# Exports
EXPOSE 5001
CMD [ "npm", "run", "dev" ]